name: Hello CodeFlow

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: yarn install
      - name: test
        run: yarn test

      - name: Show current date
        run: date
